spring:
  application:
    name: pacotes
  datasource:
    url: jdbc:h2:mem:planets
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  
  h2:
    console:
      enabled: true

      
      
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
